name: Publish NuGet Package

on:
  pull_request:
    types:
      - closed
    branches:
      - main

jobs:
  publish:
    if: github.event.pull_request.merged == true
    runs-on: codeberg-tiny

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Restore dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build --configuration Release --no-restore

      - name: Pack NuGet package
        run: dotnet pack --configuration Release --no-build --output ./nupkg

      - name: List Directory contents
        run: ls -la

#      - name: Publish to NuGet
#        run: dotnet nuget push "./nupkg/*.nupkg" \
#          --api-key "${{ secrets.NUGET_API_KEY }}" \
#          --source "https://api.nuget.org/v3/index.json"
