name: Build and Test
on: [push]
jobs:
  test:
    runs-on: codeberg-tiny
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '10.0.x'

      - name: Verify .NET Installation
        run: dotnet --info

      - name: Restore dependencies
        run: dotnet restore 

      - name: Build
        run: dotnet build --configuration Release --no-restore 

      - name: Test
        run: dotnet test 
    